# Building wheels for Linux and MacOS platforms
language: python

matrix:
  include:
    # Job generating the wheels for Linux 32bit platforms
    - sudo: required
      env:
        - CIBW_SKIP=*manylinux1_i686*
        - PIP=pip
        - PYTHON=python
      services:
        # We use docker for generating the wheels for Linux.
        - docker
    # Job generating the wheels for Linux 64bit platforms
    - sudo: required
      env:
        - CIBW_SKIP=*manylinux1_x86_64*
        - PIP=pip
        - PYTHON=python
      services:
        # We use docker for generating the wheels for Linux.
        - docker
    - os: osx
      language: generic
      env:
        - CIBW_SKIP=*cp34-*
        - PIP=pip2
        - PYTHON=python2

env:
  global:
    - TWINE_USERNAME=bmatthieu3

script:
  ### Build the wheels ###
  - $PIP install cibuildwheel==0.10.0 setuptools-rust
  - export CIBW_BEFORE_BUILD="pip install setuptools-rust && source {project}/install_cargo.sh"
  - export CIBW_ENVIRONMENT='PATH="$HOME/.cargo/bin:$PATH"'
  - cibuildwheel --output-dir dist
  ### Run the tests ###
  # Download the dependencies for compiling cdshealpix
  - $PIP install -r requirements.txt
  - $PIP install pytest setuptools-rust astropy_healpix
  # Install Rust compiler
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  # Generate the dynamic library from the cdshealpix Rust crate.
  # This will download the crate from crates.io and build it first.
  - $PYTHON setup.py build_rust
  # Move the dynamic lib to the python package folder
  - find build/ -name "*.so" -type f -exec cp {} ./cdshealpix \;
  - $PYTHON -m pytest -v cdshealpix/tests/test_healpix.py

after_success:
  # Deploy the wheels to PyPI
  - $PIP install twine
  - $PYTHON -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*.whl --skip-existing
